server:
  port: 8080

spring:
  application:
    name: meeting-app
  
  # H2 Database 설정
  datasource:
    url: jdbc:h2:mem:meetingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 Console 활성화
  h2:
    console:
      enabled: true
      path: /h2-console

 